package grpkg;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * DEPARTMENTS 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class DepartmentsClass implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** DEPARTMENT_ID. */
	private Integer departmentId;

	/** DEPARTMENT_NAME. */
	private String departmentName;

	/** EMPLOYEES. */
	private EmployeesClass managerIdemployees;

	/** LOCATION_ID. */
	private Integer locationId;

	/** EMPLOYEES 목록. */
	private Set<EmployeesClass> employeesSet;

	/**
	 * 생성자.
	 */
	public DepartmentsClass() {
		this.employeesSet = new HashSet<EmployeesClass>();
	}

	/**
	 * DEPARTMENT_ID을 설정합니다..
	 * 
	 * @param departmentId
	 *            DEPARTMENT_ID
	 */
	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	/**
	 * DEPARTMENT_ID을 가져옵니다..
	 * 
	 * @return DEPARTMENT_ID
	 */
	public Integer getDepartmentId() {
		return this.departmentId;
	}

	/**
	 * DEPARTMENT_NAME을 설정합니다..
	 * 
	 * @param departmentName
	 *            DEPARTMENT_NAME
	 */
	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	/**
	 * DEPARTMENT_NAME을 가져옵니다..
	 * 
	 * @return DEPARTMENT_NAME
	 */
	public String getDepartmentName() {
		return this.departmentName;
	}

	/**
	 * EMPLOYEES을 설정합니다..
	 * 
	 * @param managerIdemployees
	 *            EMPLOYEES
	 */
	public void setManagerIdemployees(EmployeesClass managerIdemployees) {
		this.managerIdemployees = managerIdemployees;
	}

	/**
	 * EMPLOYEES을 가져옵니다..
	 * 
	 * @return EMPLOYEES
	 */
	public EmployeesClass getManagerIdemployees() {
		return this.managerIdemployees;
	}

	/**
	 * LOCATION_ID을 설정합니다..
	 * 
	 * @param locationId
	 *            LOCATION_ID
	 */
	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	/**
	 * LOCATION_ID을 가져옵니다..
	 * 
	 * @return LOCATION_ID
	 */
	public Integer getLocationId() {
		return this.locationId;
	}

	/**
	 * EMPLOYEES 목록을 설정합니다..
	 * 
	 * @param employeesSet
	 *            EMPLOYEES 목록
	 */
	public void setEmployeesSet(Set<EmployeesClass> employeesSet) {
		this.employeesSet = employeesSet;
	}

	/**
	 * EMPLOYEES를 추가합니다..
	 * 
	 * @param employees
	 *            EMPLOYEES
	 */
	public void addEmployees(EmployeesClass employees) {
		this.employeesSet.add(employees);
	}

	/**
	 * EMPLOYEES 목록을 가져옵니다..
	 * 
	 * @return EMPLOYEES 목록
	 */
	public Set<EmployeesClass> getEmployeesSet() {
		return this.employeesSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((departmentId == null) ? 0 : departmentId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		DepartmentsClass other = (DepartmentsClass) obj;
		if (departmentId == null) {
			if (other.departmentId != null) {
				return false;
			}
		} else if (!departmentId.equals(other.departmentId)) {
			return false;
		}
		return true;
	}

}
